usr/bin/salt-call
usr/bin/spm
usr/lib/
pkg/fish-completions/salt-run.fish /usr/share/fish/vendor_completions.d
pkg/fish-completions/salt-minion.fish /usr/share/fish/vendor_completions.d
pkg/fish-completions/salt-master.fish /usr/share/fish/vendor_completions.d
pkg/fish-completions/salt-key.fish /usr/share/fish/vendor_completions.d
pkg/fish-completions/salt.fish /usr/share/fish/vendor_completions.d
pkg/fish-completions/salt-cp.fish /usr/share/fish/vendor_completions.d
pkg/fish-completions/salt-call.fish /usr/share/fish/vendor_completions.d
pkg/fish-completions/salt-syndic.fish /usr/share/fish/vendor_completions.d
pkg/fish-completions/salt_common.fish /usr/share/fish/vendor_completions.d
